### ISSUE TITLE
No network localization at all (LineageOS 15.1 MicroG)

### ISSUE THREAD

**Issue by k3lt** [microg/android_packages_apps_UnifiedNlp#157] opened 2018-05-25 14:05 UTC
The only way i can get localization is to use GPS, i'm using UnifiedNlp with Mozilla location service.
Everything is updated to latest version, MicroG self check has everything checkmarked except last entry about location, says UnifiedNlp has no last known location and UnifiedNlp do not have Location to test Geocoder, Please verify your location Backend.
I have 3G with Data enabled and also i'm connected to WiFi, my localization is enabled and set to battery saving (also tried high accuracy but doesn't do anything)
Any suggestions?

**Comment by k3lt** [comment] 2018-05-26 21:00
Fixed after installing Déjà Vu Location Service from F-Droid...

**Comment by breversa** [comment] 2018-07-09 09:21
You may want to use SatStat (https://github.com/mvglasow/satstat) to check your network location.

**Comment by ale5000-git** [comment] 2018-07-09 09:28
Try the latest versions of Mozilla and Apple backends.
In any case if the problem is fixed please close the issue.

**Closed** 2018-07-09 09:41 UTC
