### ISSUE TITLE
Send location through mock location

### ISSUE THREAD

**Issue by Almtesh** [microg/android_packages_apps_UnifiedNlp#61] opened 2016-02-13 16:56 UTC
Would it be possible to post the location from nlp through the mock location, for the device without root and with preinstalled Google services?
Mock location or any non-root way, or course.

**Comment by mar-v-in** [comment] 2016-02-13 20:44
Duplicate of #27

**Closed by mar-v-in** 2016-02-13 20:44 UTC

**Comment by Almtesh** [comment] 2016-02-13 20:51
Oh, yes, sorry for duplicate, thanks for notice.
