### ISSUE TITLE
Enabling in SailfishOS AlienDalvik

### ISSUE THREAD

**Issue by vermut** [microg/android_packages_apps_UnifiedNlp#74] opened 2016-03-13 17:46 UTC
I installed microG and some backends. 

Checklist:
- [x] Spoofing enabled
- [x] GmsCore installed
- [x] GmsCore correct signature
- [ ] GSF not installed (not needed for maps?)
- [ ] System supports location provider (Sailfish has 4.1.2 API16)
- [ ] UnifiedNlp registered in system
- [x] Location backends set up
- [x] Network-based location enabled
- [ ] No last known location

I tried to copy LegacyNetworkProvider.apk to /apps (no priv-apps here).

Where can I look next?

[Logcat starting system and launching NextBike app (which crashed)](https://gist.github.com/vermut/187184d66cdb21fe3d9b)

Some excepts:

```
I/dalvikvm( 5335): Could not find method org.microg.gms.gservices.GServicesProvider.getCallingPackage, referenced from method org.microg.gms.gservices.GServicesProvider.getCallingPackageName
W/dalvikvm( 5335): VFY: unable to resolve virtual method 32796: Lorg/microg/gms/gservices/GServicesProvider;.getCallingPackage ()Ljava/lang/String;
D/dalvikvm( 5335): VFY: replacing opcode 0x6e at 0x0006
```

```
W/ActivityManager( 5145): Permission Denial: Accessing service ComponentInfo{com.google.android.gms/org.microg.gms.gcm.PushRegisterService} from pid=5575, uid=10016 requires com.google.android.c2dm.permission.RECEIVE
W/dalvikvm( 5575): threadid=10: thread exiting with uncaught exception (group=0x40b61360)
E/AndroidRuntime( 5575): FATAL EXCEPTION: AsyncTask #1
E/AndroidRuntime( 5575): java.lang.RuntimeException: An error occured while executing doInBackground()
E/AndroidRuntime( 5575):    at android.os.AsyncTask$3.done(AsyncTask.java:299)
E/AndroidRuntime( 5575):    at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
E/AndroidRuntime( 5575):    at java.util.concurrent.FutureTask.setException(FutureTask.java:124)
E/AndroidRuntime( 5575):    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
E/AndroidRuntime( 5575):    at java.util.concurrent.FutureTask.run(FutureTask.java:137)
E/AndroidRuntime( 5575):    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
E/AndroidRuntime( 5575):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
E/AndroidRuntime( 5575):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
E/AndroidRuntime( 5575):    at java.lang.Thread.run(Thread.java:856)
E/AndroidRuntime( 5575): Caused by: java.lang.SecurityException: Not allowed to start service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms (has extras) } without permission com.google.android.c2dm.permission.RECEIVE
E/AndroidRuntime( 5575):    at android.app.ContextImpl.startService(ContextImpl.java:1167)
E/AndroidRuntime( 5575):    at android.content.ContextWrapper.startService(ContextWrapper.java:383)
E/AndroidRuntime( 5575):    at com.google.android.gms.b.a.c(Unknown Source)
E/AndroidRuntime( 5575):    at com.google.android.gms.b.a.a(Unknown Source)
E/AndroidRuntime( 5575):    at de.nextbike.b.c.a(Unknown Source)
E/AndroidRuntime( 5575):    at de.nextbike.b.c.doInBackground(Unknown Source)
E/AndroidRuntime( 5575):    at android.os.AsyncTask$2.call(AsyncTask.java:287)
E/AndroidRuntime( 5575):    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
E/AndroidRuntime( 5575):    ... 5 more

```

**Comment by vermut** [comment] 2016-03-13 21:01
P.S. Also seen
```
W/GmsMapView( 8366): java.lang.NoSuchFieldException: primaryCpuAbi
W/GmsMapView( 8366): 	at java.lang.Class.getField(Class.java:787)
W/GmsMapView( 8366): 	at org.microg.gms.maps.BackendMapView.loadNativeLib(BackendMapView.java:65)
W/GmsMapView( 8366): 	at org.microg.gms.maps.BackendMapView.<init>(BackendMapView.java:121)
W/GmsMapView( 8366): 	at org.microg.gms.maps.BackendMap.<init>(BackendMap.java:70)
W/GmsMapView( 8366): 	at org.microg.gms.maps.GoogleMapImpl.<init>(GoogleMapImpl.java:135)
W/GmsMapView( 8366): 	at org.microg.gms.maps.MapFragmentImpl.onCreateView(MapFragmentImpl.java:73)
W/GmsMapView( 8366): 	at com.google.android.gms.maps.internal.IMapFragmentDelegate$Stub.onTransact(IMapFragmentDelegate.java:104)
W/GmsMapView( 8366): 	at android.os.Binder.transact(Binder.java:326)
W/GmsMapView( 8366): 	at com.google.android.gms.maps.internal.IMapFragmentDelegate$zza$zza.onCreateView(Unknown Source)
W/GmsMapView( 8366): 	at com.google.android.gms.maps.SupportMapFragment$zza.onCreateView(Unknown Source)
W/GmsMapView( 8366): 	at com.google.android.gms.dynamic.zza$4.zzb(Unknown Source)
W/GmsMapView( 8366): 	at com.google.android.gms.dynamic.zza.zza(Unknown Source)
W/GmsMapView( 8366): 	at com.google.android.gms.dynamic.zza.onCreateView(Unknown Source)
W/GmsMapView( 8366): 	at com.google.android.gms.maps.SupportMapFragment.onCreateView(Unknown Source)
W/GmsMapView( 8366): 	at ee.mtakso.client.view.MTaksoMapFragment.onCreateView(MTaksoMapFragment.java:25)
W/GmsMapView( 8366): 	at android.support.v4.app.Fragment.performCreateView(Fragment.java:1789)
W/GmsMapView( 8366): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:924)
W/GmsMapView( 8366): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1116)
W/GmsMapView( 8366): 	at android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java:1218)
W/GmsMapView( 8366): 	at android.support.v4.app.FragmentManagerImpl.onCreateView(FragmentManager.java:2170)
W/GmsMapView( 8366): 	at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:300)
W/GmsMapView( 8366): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:676)
W/GmsMapView( 8366): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
W/GmsMapView( 8366): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
W/GmsMapView( 8366): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
W/GmsMapView( 8366): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
W/GmsMapView( 8366): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
W/GmsMapView( 8366): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
W/GmsMapView( 8366): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
W/GmsMapView( 8366): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
W/GmsMapView( 8366): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
W/GmsMapView( 8366): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
W/GmsMapView( 8366): 	at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:256)
W/GmsMapView( 8366): 	at android.app.Activity.setContentView(Activity.java:1867)
W/GmsMapView( 8366): 	at ee.mtakso.client.activity.MapActivity.onCreate(MapActivity.java:136)
W/GmsMapView( 8366): 	at android.app.Activity.performCreate(Activity.java:5008)
W/GmsMapView( 8366): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
W/GmsMapView( 8366): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2030)
W/GmsMapView( 8366): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2091)
W/GmsMapView( 8366): 	at android.app.ActivityThread.access$600(ActivityThread.java:137)
W/GmsMapView( 8366): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202)
W/GmsMapView( 8366): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/GmsMapView( 8366): 	at android.os.Looper.loop(Looper.java:137)
W/GmsMapView( 8366): 	at android.app.ActivityThread.main(ActivityThread.java:4781)
W/GmsMapView( 8366): 	at java.lang.reflect.Method.invokeNative(Native Method)
W/GmsMapView( 8366): 	at java.lang.reflect.Method.invoke(Method.java:511)
W/GmsMapView( 8366): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:805)
W/GmsMapView( 8366): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:568)
W/GmsMapView( 8366): 	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by mar-v-in** [comment] 2016-03-14 12:51
The mentioned excerpts from log actually belong to GmsCore (this repo is for issues with UnifiedNlp):
1. getCallingPackage: This is fine and not a problem, it only affects log output
2. Permission Denial: this happens when apps installed before GmsCore try to use GCM. You need to reinstall these apps to give them permission to do so.
3. primaryCpuAbi: This is a warning that the system has no proper support for multilib - only interesting when the CPU has 64 bit.

- GSF is not required for Maps, only few older apps require it for push messaging.
- System supports location provider > This means that the system has no support for custom location providers. I guess sailfish somehow uses a native solution for geolocation and forwards locations to AlienDalvik?
- UnifiedNlp registered > reason see above

Summary: reinstalling NextBike *should* fix the crashing issue (or atleast give you some new errors)
How did you manage to use signature spoofing on Sailfish/AlienDalvik?

**Comment by vermut** [comment] 2016-03-14 17:08
**NextBike**: Much better. After reinstalling I see phone launching GPS and reporting more or less accurate coordinates. The map also is visible (looks like it OSM).
But no markers. 

I see them in the logs:
```
D/GmsMapMarkerImpl( 6939): New marker m8 with title Valnu/ Kalku ielas krustojums @ lat/lng: (56.9503166573584,24.1116642951965)
D/BitmapDescriptor( 6939): Start loading org.microg.gms.maps.bitmap.ResourceBitmapDescriptor@42192610
D/BitmapDescriptor( 6939): Done loading org.microg.gms.maps.bitmap.ResourceBitmapDescriptor@42192610
D/GmsMapMarkerImpl( 6939): New marker m9 with title Elizabetes/ Pulkveza Brieza ielas krustojums @ lat/lng: (56.958600955466544,24.105688333511353)
D/GmsMapMarkerImpl( 6939): New marker m10 with title Kongresu nams, Krisjana Valdemara iela 5 @ lat/lng: (56.9546872050993,24.1083383560181)
D/BitmapDescriptor( 6939): Start loading org.microg.gms.maps.bitmap.ResourceBitmapDescriptor@421925e0
D/skia    ( 6939): --- SkImageDecoder::Factory returned null
D/BitmapDescriptor( 6939): Done loading org.microg.gms.maps.bitmap.ResourceBitmapDescriptor@421925e0
D/GmsMapMarkerImpl( 6939): New marker m11 with title Citadele banka, Republikas laukums 2a @ lat/lng: (56.95376574670144,24.10050630569458)
D/GmsMapMarkerImpl( 6939): New marker m12 with title Doma laukums @ lat/lng: (56.94931024714476,24.104851484298706)
D/BitmapDescriptor( 6939): Start loading org.microg.gms.maps.bitmap.ResourceBitmapDescriptor@421925e0
D/skia    ( 6939): --- SkImageDecoder::Factory returned null
D/BitmapDescriptor( 6939): Done loading org.microg.gms.maps.bitmap.ResourceBitmapDescriptor@421925e0
```

But don't see them on respective map areas.

**Comment by vermut** [comment] 2016-03-14 17:10
**Signature Spoofing**: I managed to deodex framework and apps (using Universal Deodexer V5) and patched framework.jar with patched version of Needle patch. 

If someone seriously interested it this I can provide it with more-or-less automated package or just secretly upload /opt/alien/system somewhere.

**Comment by vermut** [comment] 2016-03-14 17:28
**Taxify**: more difficult case. Freshly reinstalled.
Starts and shows the big map. Claims to start searching for GPS but phone is not showing GPS icon. [Logs](https://gist.github.com/vermut/fdb399024d27e9b82247)

When I search location by address, correctly suggests venues around (via custom forsquare lookup) [and then crashes.](https://gist.github.com/vermut/13a7cf410af778271895)

**Comment by vermut** [comment] 2016-03-14 17:34
**Untappd**: works very good. Crashes when asking to "show directions"
```
I/ActivityManager( 5917): START {act=android.intent.action.VIEW dat=http://maps.google.com/maps?saddr=56.97066906,24.15900079&daddr=56.9613,24.1299 cmp=com.google.android.apps.maps/com.google.android.maps.MapsActivity u=0} from pid 8530
E/PluginManager( 8530): Uncaught exception from plugin
E/PluginManager( 8530): android.content.ActivityNotFoundException: Unable to find explicit activity class {com.google.android.apps.maps/com.google.android.maps.MapsActivity}; have you declared this activity in your AndroidManifest.xml?
E/PluginManager( 8530):         at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1541)
E/PluginManager( 8530):         at android.app.Instrumentation.execStartActivity(Instrumentation.java:1416)
E/PluginManager( 8530):         at android.app.Activity.startActivityForResult(Activity.java:3351)
E/PluginManager( 8530):         at android.app.Activity.startActivityForResult(Activity.java:3312)
E/PluginManager( 8530):         at android.app.Activity.startActivity(Activity.java:3522)
E/PluginManager( 8530):         at android.app.Activity.startActivity(Activity.java:3490)
E/PluginManager( 8530):         at com.borismus.webintent.WebIntent.startActivity(WebIntent.java:194)
E/PluginManager( 8530):         at com.borismus.webintent.WebIntent.execute(WebIntent.java:71)
E/PluginManager( 8530):         at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:84)
E/PluginManager( 8530):         at org.apache.cordova.PluginManager.exec(PluginManager.java:147)
E/PluginManager( 8530):         at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
E/PluginManager( 8530):         at org.apache.cordova.CordovaBridge.promptOnJsPrompt(CordovaBridge.java:129)
E/PluginManager( 8530):         at org.apache.cordova.CordovaChromeClient.onJsPrompt(CordovaChromeClient.java:192)
E/PluginManager( 8530):         at android.webkit.CallbackProxy.handleMessage(CallbackProxy.java:655)
E/PluginManager( 8530):         at android.os.Handler.dispatchMessage(Handler.java:99)
E/PluginManager( 8530):         at android.os.Looper.loop(Looper.java:137)
E/PluginManager( 8530):         at android.app.ActivityThread.main(ActivityThread.java:4781)
E/PluginManager( 8530):         at java.lang.reflect.Method.invokeNative(Native Method)
E/PluginManager( 8530):         at java.lang.reflect.Method.invoke(Method.java:511)
E/PluginManager( 8530):         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:805)
E/PluginManager( 8530):         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:568)
E/PluginManager( 8530):         at dalvik.system.NativeStart.main(Native Method)
D/GpsLocationProvider( 5917): Gps MessageHandler. msg.what 3 msg.arg1:0 msg.arg2: 1
```

**Comment by mar-v-in** [comment] 2016-03-14 17:43
@ NextBike: I can reproduce markers not correctly displayed on my device. WIll provide a fix soon.
@ Taxify: I'll further investigate this one...
@ Untappd: You are missing a maps application. Seems like Untappd expects atleast one Maps app to be installed and crashes if not. You need a maps application (not necassarily Google Maps, OsmAnd should be fine as well) to use the show directions feature.

**Comment by vermut** [comment] 2016-03-14 17:43
**System supports location provider** > This means that the system has no support for custom location providers. I guess sailfish somehow uses a native solution for geolocation and forwards locations to AlienDalvik?

Probably... How can I change it? Fix it? Or it's not a problem? Is there a good application to test all maps issues?

**Comment by n76** [comment] 2016-03-14 17:49
FWIW, my impression is that Maps.me does a bit better at handling geo intents than OsmAnd. Either of those (and probably other mapping apps) should work though.

**Comment by mar-v-in** [comment] 2016-03-14 17:51
I don't have a sailfish device here for testing. Can you check if SatStat app displays two locations (red = gps, blue = network)? If you only see the red one, this is something we might want to address. Check issue #55 on how to add support for custom location providers if system does not (this requires some framework resource hacking as you can't compile from source, but i'm sure there are tools to do these kind of stuff)

**Comment by mar-v-in** [comment] 2016-03-14 18:41
NextBike should be fixed as of 51b8d38, you can download latest preview release (v0.2.1-12+) here: https://microg.org/download.html

**Comment by vermut** [comment] 2016-03-14 20:53
@ SatStat: first compass screen shows red and blue dots. That's it?
```
Third screen died with
E/AndroidRuntime(14308): java.lang.IllegalArgumentException: zoomLevel must not be negative: -1
E/AndroidRuntime(14308): 	at org.mapsforge.map.model.MapViewPosition.setZoomLevel(MapViewPosition.java:394)
E/AndroidRuntime(14308): 	at com.vonglasow.michael.satstat.MainActivity.updateMap(MainActivity.java:1999)
E/AndroidRuntime(14308): 	at com.vonglasow.michael.satstat.MainActivity.onLocationChanged(MainActivity.java:1217)
E/AndroidRuntime(14308): 	at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:263)
E/AndroidRuntime(14308): 	at android.location.LocationManager$ListenerTransport.access$000(LocationManager.java:196)
E/AndroidRuntime(14308): 	at android.location.LocationManager$ListenerTransport$1.handleMessage(LocationManager.java:212)
E/AndroidRuntime(14308): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(14308): 	at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime(14308): 	at android.app.ActivityThread.main(ActivityThread.java:4781)
E/AndroidRuntime(14308): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(14308): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(14308): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:805)
E/AndroidRuntime(14308): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:568)
E/AndroidRuntime(14308): 	at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager( 5917):   Force finishing activity com.vonglasow.michael.satstat/.MainActivity
W/ActivityManager( 5917): Activity pause timeout for ActivityRecord{41d8d058 surfaceId:14 com.vonglasow.michael.satstat/.MainActivity}
I/ActivityManager( 5917): ACTIVITY DESTROYING: r = ActivityRecord{41d8d058 surfaceId:14 com.vonglasow.michael.satstat/.MainActivity}, index = 3
D/ActivityManager( 5917): notifySurfaceDiedIfNeeded( 3) : ActivityRecord{41d8d058 surfaceId:14 com.vonglasow.michael.satstat/.MainActivity}
```

**Comment by vermut** [comment] 2016-03-14 21:06
@ NextBike: confirmed working markers with v0.2.1-12
@ Untappd: installing OsmAnd~ from F-Droid changed nothing.

**Comment by mar-v-in** [comment] 2016-03-14 21:22
@ SatStat I meant the third screen, no idea why it crashes, can you file a bug report at https://github.com/mvglasow/satstat/issues as this is not related to microG? Thanks.

@ Untappd: You are right and I was wrong. In fact Untappd requires original Google Maps to be installed for directions. You might want to contact the developer to consider systems that don't have Google Maps by not sending the component string "cmp=com.google.android.apps.maps/com.google.android.maps.MapsActivity" with the starting intent.

We should consider to have a small tool in the future that collects intents targeted at Google Maps and forwards them to a Maps application of your choice. Or even use the maps rendering implemented in GmsCore to do a small maps app. But both is rather low priority for now.

**Comment by vermut** [comment] 2016-03-17 12:23
Any luck with Taxify? This app was a reason I started all this :)

**Comment by BenTGNU** [comment] 2016-07-21 08:07
> vermut commented on 14 Mar 
 If someone seriously interested it this I can provide it with more-or-less automated package or just secretly upload /opt/alien/system somewhere.

If you have some time, I'd like to get your package or upload. I assume that this is for jolla1 ?
Because I tried to do the same, I manage to deodex but not to patch framework.jar, I probably missed something.

In advance, Thanks :)

**Comment by vermut** [comment] 2016-07-21 08:24
Yes, Jolla1. Are patching using Needle patch? You will need my branch with Jolla specific stuff: https://github.com/moosd/Needle/pull/9

BTW, latest microG almost works with latest Taxify. So the main goal - achieved!

**Comment by ale5000-git** [comment] 2016-08-12 17:44
@vermut I have included your patch in my fork of Needle, it would be nice if you can test if it is working, it is here: https://github.com/ale5000-git/Tingle

**Comment by nomeata** [comment] 2016-11-23 00:43
> Signature Spoofing: I managed to deodex framework and apps (using Universal Deodexer V5) and patched framework.jar with patched version of Needle patch. 

Is there an alternative to the Universal Deodexer V5? Maybe one that runs on the phone, or on Linux?

**Comment by mar-v-in** [comment] 2017-01-29 09:13
Closing this as it's not related to UnifiedNlp, if there are still open problems regarding GmsCore, please report back in the corresponding repo.

**Closed by mar-v-in** 2017-01-29 09:13 UTC

**Comment by evanstapler** [comment] 2017-01-29 12:25
Hello worlds.

**Comment by evanstapler** [comment] 2017-01-29 12:26
I don't typically use GitHub, am I supposed to be comment on a closed issue?

**Comment by mar-v-in** [comment] 2017-01-29 12:30
If it's related, feel free, don't ask to ask.

**Comment by evanstapler** [comment] 2017-01-31 01:50
I do not fully understand, but I am very interested in learning; how do i just move forward into trying these new services?

**Comment by evanstapler** [comment] 2017-01-31 01:51
If i could answeer /my own question this is where I woudld dp so.

**Comment by ale5000-git** [comment] 2017-01-31 01:59
@evanstapler: For generic questions I suggest to ask [here](https://forum.xda-developers.com/showthread.php?t=2991544).
